### ISSUE TITLE
Please delete `refs/tags/refs/heads/main`

### ISSUE THREAD

**Issue by jsoref** [github/github-artifact-exporter#54]
There's a tag called `refs/heads/main`

It's confusing some of my scripts.

I can't imagine that this tag is intentional

**Comment by Chocrates** [comment]
Hey @jsoref let me talk with the other maintainers.  I don't recall why this exists, perhaps it was an accident yeah.

**Comment by Chocrates** [comment]
Tag  has been deleted.  Still not sure why/how it was created but I hope it unbreaks your scripts.
