### ISSUE TITLE
What the hell was that

### ISSUE THREAD

**Issue by tied2token** [github/github-artifact-exporter#60]
Iam not sure what it was saying over and over agian

**Comment by zkoppert** [comment]
Did you have an error message? We will need a bit more description to go somewhere with this issue.

**Comment by tied2token** [comment]
It was a huge huge list of I was just trying to compile or check may json app can you look at it or do you need some kind of Pic or l8nk?

**Comment by zkoppert** [comment]
yes, either would be helpful
