### ISSUE TITLE
Export support for Discussions

### ISSUE THREAD

**Issue by crfoxeam** [github/github-artifact-exporter#72]
Hello! Thanks for the great tool.

Pull requests and issues are searchable by [`type` and `is` qualifier](https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-only-issues-or-pull-requests).
Furthermore, I have confirmed that the issue has already been realized and that there is a request for a pull request as well.

Here I thought it would be nice to also have the ability to export Discussions.
I think that exporting discussions would be just as beneficial as exporting issues, in that the discussion minutes could be easily moved to another location.
On the other hand, Discussions don't seem to be searchable by `is` or `type`. Is exporting Discussions feasible in GitHub at this stage?

Thanks!

**Comment by zkoppert** [comment]
I don't currently see a way to export discussions from GitHub at this time.
